### ISSUE TITLE
BMVC with wire money transfer

### ISSUE THREAD

**Issue by jprimke** [DmitryEfimenko/DmitryEfimenko.github.io#1]
Hello Dmitry

We would buy your BMVC via wire transfer. It is possible?

Thanks for your assistance,

Regards

Joerg

**Comment by DmitryEfimenko** [comment]
Sure we can make it work. Please contact me directly through my email address (found at the end of [this page](https://www.twitterbootstrapmvc.com/Documentation/LicenseTerms))
